# Asciidoc Code samples
:Author: Benoît Courtine
:Email: contact@courtine.org
:Date: 2017-03-06
:Revision: 1.0
:page-tags: [asciidoc,formatting]
:page-keywords: code samples syntax highlighting
:page-summary: "You can use fenced code blocks with the language specified."
:page-sidebar: asciidoc_sidebar
:page-permalink: asciidoc_code_samples.html

## Code Samples

Use source blocks with the language specified, like this:

[source]
----
 [source, js]
 ----
 console.log('hello');
 ----
----

**Result:**

[source, js]
----
console.log('hello');
----

For the list of supported languages you can use (similar to `js` for JavaScript), see
https://github.com/jneen/rouge/wiki/list-of-supported-languages-and-lexers[Supported languages].

## Source line numbers

[source]
----
 [source, js, numbered]
 ----
 console.log('hello');
 console.log(' ');
 console.log('world');
 ----
----

Here is the result:

[source, js, numbered]
----
console.log('hello');
console.log(' ');
console.log('world');
----

## Source comments

[source]
----
 [source, js, numbered]
 ----
 console.log('hello'); // \<1>
 console.log(' ');
 console.log('world'); // \<2>
 ----
 <1> First line comment
 <2> Third line comment
----

Here is the result:

[source, js, numbered]
----
console.log('hello'); // <1>
console.log(' ');
console.log('world'); // <2>
----
<1> First line comment
<2> Third line comment

## TODO

Some Asciidoc styles conflict with theme native styles:

* Numbered source code table (`backgroup-color` and `border-top`).
* Code comment boxes vertical alignment.

IMPORTANT: Theses conflicts should be identified and resolved.

Markdown uses `Rouge` code highlighter, with the `syntax.css` CSS file. Asciidoc uses `Pygments` code highlighter,
with the `asciidoc-pygments.css` CSS file.

IMPORTANT: Code highlighters and highlight CSS files should be unified.
