= Asciidoc Alerts
:Author: Benoît Courtine
:Email: contact@courtine.org
:Date: 2017-03-02
:Revision: 1.0
:page-tags: [asciidoc,formatting]
:page-keywords:
:page-summary: "You can insert notes, tips, warnings, and important alerts in your content. These notes make use of Bootstrap styling."
:page-sidebar: asciidoc_sidebar
:page-permalink: asciidoc_alerts.html
:page-liquid:

== About alerts

Alerts are little warnings, info, or other messages that you have called out in special formatting.

== Alerts

Alerts are a native function of Asciidoc syntax: see the "admonition" section of the
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#more-delimited-blocks[Syntax Quick Reference Guide].

=== Single paragraph alerts

[source]
----
NOTE: This is my note. All the content I type here is treated as a single paragraph.
----

Here's the result:

NOTE: This is my note. All the content I type here is treated as a single paragraph.

=== Multiple paragraph alerts

Using the block syntax, an alert can contain multiple paragraphs with complex formatting (lists, tables, etc.).

[source]
----
[TIP]
====
Here is my tip.

With a second paragraph... and a list:

* Item 1
* Item 2
====
----

Here is the result:

[TIP]
====
Here is my tip.

With a second paragraph, and a list:

* Item 1
* Item 2
====

=== Types of alerts available

There are five types of alerts you can leverage:

* NOTE
* TIP
* CAUTION (using the WARNING style, since Bootstrap provides only 4 different alert styles)
* WARNING
* IMPORTANT

Here is the result for each type:

NOTE: This is my note. All the content I type here is treated as a single paragraph.

TIP: This is my tip. All the content I type here is treated as a single paragraph.

CAUTION: This is my caution. All the content I type here is treated as a single paragraph.

WARNING: This is my warning. All the content I type here is treated as a single paragraph.

IMPORTANT: This is my important message. All the content I type here is treated as a single paragraph.

== Callouts

=== Usage

CAUTION: Bootstrap has 6 callout types, but since Asciidoc has only 5 alert blocks, the `primary` Bootstrap callout
cannot be generated using Asciidoc syntax. The excluded callout can be changed editing the
`templates/block_admonition.html.erb` file.

[source]
----
[NOTE.callout]
====
A note using the Bootstrap callout style.
====
----

Here's the result:

[NOTE.callout]
====
A note using the Bootstrap callout style.
====

CAUTION: With an additional style to the admonition block (here `callout`), the single line syntax is not supported.

As for alerts, callout blocks can contain complex formatting: lists, tables, code samples, etc.

----
[TIP.callout]
====
A tip with nested lists:

* Item 1
.. Sub-item 1
.. Sub-item 2
* Item 2
====
----

Here is the result:

[TIP.callout]
====
A tip with *nested lists*:

* Item 1
.. Sub-item 1
.. Sub-item 2
* Item 2
====

NOTE: It's just a stylistic preference whether to use an alert or callout.

=== Callout types

The available callout types are :

* `NOTE.callout`: Bootstrap `info` callout (light blue)
* `TIP.callout`: Bootstrap `success` callout (green)
* `CAUTION.callout`: Bootstrap `default` callout (grey)
* `WARNING.callout`: Bootstrap `warning` callout (yellow)
* `IMPORTANT.callout`: Bootstrap `danger` callout (red)
* Bootstrap `primary` callout (dark blue) cannot be rendered

Here's the result for each type:

[NOTE.callout]
====
Note callout
====

[TIP.callout]
====
Tip callout
====

[CAUTION.callout]
====
Caution callout.
====

[WARNING.callout]
====
Warning callout.
====

[IMPORTANT.callout]
====
Important callout.
====

== Alert and callout rendering

Alert and callout rendering style can be updated, editing the `_templates/block_admonition.html.erb` template file.

NOTE: When link:asciidoc_generating_pdfs.html[generating a PDF with Asciidoctor PDF], alerts and callouts with have
the same rendering (default Asciidoc admonition rendering), since theme specific HTML templates are ignored by the
PDF backend.

== Use Liquid variables inside parameters with includes

[IMPORTANT]
====
* In order to use liquid variables and filters, the page header must contain the `page-liquid` attribute.
* Liquid variables and filters are not processed when
link:asciidoc_generating_pdfs.html[generating a PDF with Asciidoctor PDF]. If you whant to use the Asciidoctor PDF
feature, usage of Liquid variables is not recommanded.
====

'''

.Liquid variable usage example
[source]
----
{% raw %}NOTE: The "{{ site.company_name }}" is pleased to announce an upcoming release.{% endraw %}
----

Here is the result:

NOTE: The "{{ site.company_name }}" is pleased to announce an upcoming release.
