# Asciidoc Pages
:Author: Benoît Courtine
:Email: contact@courtine.org
:Date: 2017-03-07
:Revision: 1.0
:page-tags: [asciidoc, getting_started, formatting]
:page-keywords: pages, authoring, exclusion, frontmatter
:page-summary: "This theme primarily uses pages. You need to make sure your pages have the appropriate frontmatter. One frontmatter tag your users might find helpful is the summary tag. This functions similar in purpose to the shortdesc element in DITA."
:page-sidebar: asciidoc_sidebar
:page-permalink: asciidoc_pages.html
:toc: macro

## Where to author content
Use a text editor such as Sublime Text, WebStorm, IntelliJ, or Atom to create pages. Atom is recommended because it's
created by Github, which is driving some of the Jekyll development through Github Pages.

TIP: IMHO, Atom have the best Asciidoc support (using plugins).

## Where to save pages

You can store your pages in any folder structures you want, with any level of folder nesting. The site output will pull
all of those pages out of their folders and put them into the root directory. Check out the \_site folder, which is
where Jekyll is generated, to see the difference between your project's structure and the resulting site output.

NOTE: The theme suggestion is to place all pages in a directory structure under the `pages` folder.

The listing of all pages in the root directory (which happens when you add a permalink property to the pages) is what
allows the relative linking and offline viewing of the site to work.

## Frontmatter

Make sure each page has frontmatter at the top like this:

[source, yaml]
----
= Title
:Author: Benoît Courtine
:Email: contact@courtine.org
:Date: 2017-03-07
:Revision: 1.0
:page-tags: [formatting, getting_started]
:page-keywords: notes, tips, cautions, warnings, admonitions
:page-last_updated: March 7, 2017
:page-summary: "You can insert notes, tips, warnings, and important alerts in your content."
:page-sidebar: asciidoc_sidebar
:page-permalink: asciidoc_pages.html
:toc: macro
----

Your frontmatter must have a `title` and `page-permalink` value. All the other values are optional.

IMPORTANT: `Author`, `Email`, `Date`, and `Revision` are standard (but optional) Asciidoc variables. Jekyll variables
in Asciidoc frontmatter must be prefixed with `page-` to be processed correctly. For more information, see
https://github.com/asciidoctor/jekyll-asciidoc#page-attributes[Jekyll Asciidoc plugin page attributes section].

Frontmatter properties are explained here: link:mydoc_pages.html[Pages].

## Automatic mini-TOCs

By default, Asciidoc generates a TOC at the top of your pages and posts. This feature is disabled in `_config.yml`,
because Asciidoc TOC conflicts with theme TOC.
If you prefer the Asciidoc TOC, you can put theses properties in the frontmatter:

[source, yaml]
----
:page-toc: false
:toc: auto
----

TIP: Setting the Asciidoc `toc` property to `macro`, you can insert the TOC at the place of you choice in the document,
using the `toc::[]` macro.

.Toc inserted here by the macro
toc::[]

## Headings

Use pound signs before the heading title to designate the level. Note that kramdown requires headings to have one space
before and after the heading. Without this space above and below, the heading won't render into HTML.

[source]
----
## Second-level heading

### Third-level heading

#### Fourth-level heading
----

## Specify a particular page layout

The configuration file sets the default layout for pages as the "page" layout.

You can create other layouts inside the `layouts` folder. If you create a new layout, you can specify that
your page use your new layout by adding `:page-layout: mylayout.html` in the page's frontmatter. Whatever layout you
specify in the frontmatter of a page will override the layout default set in the configuration file.

## Comments

Disqus, a commenting system, is integrated into the theme. In the configuration file, specify the Disqus code for
the universal code, and Disqus will appear. If you don't add a Disqus value, the Disqus form isn't included.
